Machine Learning Zoomcamp

Introduction to Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.14.2/lib/python3.14/site-packages/numpy/__init__.py'>

Creating Arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 12])

In [10]:
a

array([ 1,  2,  3,  5,  7, 12])

In [13]:
a[3] = 10

In [14]:
a

array([ 1,  2,  3, 10,  7, 12])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])